import "~/styles/globals.css";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { NextUIProvider } from "@nextui-org/system";
import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={`${GeistSans.variable}`}>
			<body>
				<NextUIProvider>
					<TRPCReactProvider>
						<main className="flex min-h-screen flex-col bg-gradient-to-b from-[#2e026d] to-[#0f1020] text-white">
							{children}
						</main>
					</TRPCReactProvider>
				</NextUIProvider>
			</body>
		</html>
	);
}
