export const MOCK_USER_DETAILS_JSON = {
	data: [
		{
			id: 1,
			full_name: "Jared Bahringer",
			email: "Jared_Bahringer@gmail.com",
			address: { street: "0980 Lizzie Village", city: "Čajniče" },
		},
		{
			id: 2,
			full_name: "Lionel O'Kon",
			email: "Lionel_Reynolds4@yahoo.com",
			address: { street: "2944 William Expressway", city: "Kingstown" },
		},
		{
			id: 3,
			full_name: "Abraham Morissette",
			email: "Abraham.Morissette@gmail.com",
			address: { street: "171 Pfeffer Route", city: "Laventille" },
		},
		{
			id: 4,
			full_name: "Dan Hand",
			email: "Dan.Hand94@yahoo.com",
			address: { street: "9547 Flavie Cliffs", city: "Chortoq Shahri" },
		},
		{
			id: 5,
			full_name: "Alonzo Kozey",
			email: "Alonzo_Kozey@hotmail.com",
			address: { street: "0220 Huels Station", city: "Földes" },
		},
		{
			id: 6,
			full_name: "Angie Feest",
			email: "Angie63@gmail.com",
			address: { street: "4971 Rodriguez Oval", city: "Saint Peters" },
		},
		{
			id: 7,
			full_name: "Joann Little",
			email: "Joann24@hotmail.com",
			address: { street: "807 Marlin Mission", city: "Bubanza" },
		},
		{
			id: 8,
			full_name: "Arnold Dooley",
			email: "Arnold_Dooley@yahoo.com",
			address: { street: "2297 Berge Underpass", city: "Probishtip" },
		},
		{
			id: 9,
			full_name: "Norman Farrell",
			email: "Norman12@gmail.com",
			address: { street: "8298 Carlie Gardens", city: "Nkoaranga" },
		},
		{
			id: 10,
			full_name: "Amanda Conroy",
			email: "Amanda.Conroy11@gmail.com",
			address: { street: "4217 Bogisich Wells", city: "Marka" },
		},
		{
			id: 11,
			full_name: "Darla Schaefer",
			email: "Darla.Schaefer@yahoo.com",
			address: { street: "26984 Runte Spurs", city: "Quebrada de Loro" },
		},
		{
			id: 12,
			full_name: "Floyd Jenkins",
			email: "Floyd.Jenkins@gmail.com",
			address: { street: "864 Schneider Ramp", city: "Gustavia" },
		},
		{
			id: 13,
			full_name: "Frankie Powlowski",
			email: "Frankie61@yahoo.com",
			address: { street: "222 Muhammad Shoal", city: "Kasempa" },
		},
		{
			id: 14,
			full_name: "Franklin Carter",
			email: "Franklin.Carter84@yahoo.com",
			address: { street: "0320 Ben Roads", city: "Marigot" },
		},
		{
			id: 15,
			full_name: "Glenn Doyle",
			email: "Glenn28@hotmail.com",
			address: { street: "80873 Langosh Rue", city: "Castelldefels" },
		},
		{
			id: 16,
			full_name: "Salvatore Rutherford",
			email: "Salvatore.Rutherford48@hotmail.com",
			address: { street: "062 Feeney Mall", city: "Iquique" },
		},
		{
			id: 17,
			full_name: "Perry Kuhic",
			email: "Perry_Kuhic93@hotmail.com",
			address: { street: "9561 Becker Causeway", city: "Al Hilāliyya" },
		},
		{
			id: 18,
			full_name: "Ollie Hodkiewicz",
			email: "Ollie_Hodkiewicz@gmail.com",
			address: { street: "111 Adan Skyway", city: "Saint Saviour" },
		},
		{
			id: 19,
			full_name: "Harry Kuhlman",
			email: "Harry_Kuhlman@gmail.com",
			address: { street: "1224 Romaguera Road", city: "Zedelgem" },
		},
		{
			id: 20,
			full_name: "Rochelle Johns",
			email: "Rochelle.Johns@yahoo.com",
			address: { street: "8360 Lily Forge", city: "Al Madīd" },
		},
		{
			id: 21,
			full_name: "Jeanne Jacobs",
			email: "Jeanne44@hotmail.com",
			address: { street: "5275 O'Hara Flat", city: "Akranes" },
		},
		{
			id: 22,
			full_name: "Jennie Mueller",
			email: "Jennie.Mueller62@gmail.com",
			address: { street: "267 Christ Islands", city: "Koun-Fao" },
		},
		{
			id: 23,
			full_name: "Jeffery Jakubowski",
			email: "Jeffery41@hotmail.com",
			address: { street: "2543 Valentina Village", city: "Ulimang" },
		},
		{
			id: 24,
			full_name: "Delbert Reichert",
			email: "Delbert.Reichert76@yahoo.com",
			address: { street: "76128 Amari Haven", city: "Zinder" },
		},
		{
			id: 25,
			full_name: "Lloyd Mueller",
			email: "Lloyd.Mueller@hotmail.com",
			address: { street: "469 Larkin Lane", city: "Al Wakrah" },
		},
		{
			id: 26,
			full_name: "Marvin Cremin",
			email: "Marvin.Cremin1@gmail.com",
			address: { street: "844 Jacklyn Pine", city: "Pietà" },
		},
		{
			id: 27,
			full_name: "Antonio Gottlieb",
			email: "Antonio2@yahoo.com",
			address: { street: "054 Jacobi Spring", city: "Grytviken" },
		},
		{
			id: 28,
			full_name: "Corey Walter",
			email: "Corey44@yahoo.com",
			address: { street: "2917 Waldo Dam", city: "Saint-François" },
		},
		{
			id: 29,
			full_name: "Roman Bernier",
			email: "Roman_Bernier@gmail.com",
			address: { street: "629 Kris Shoal", city: "Zhongxing New Village" },
		},
		{
			id: 30,
			full_name: "Cassandra Braun",
			email: "Cassandra.Braun67@gmail.com",
			address: { street: "4912 McClure Forks", city: "Mineros" },
		},
		{
			id: 31,
			full_name: "Velma Pfannerstill",
			email: "Velma_Pfannerstill17@yahoo.com",
			address: { street: "4565 Skiles Parks", city: "Tsingoni" },
		},
		{
			id: 32,
			full_name: "Tomas Morissette",
			email: "Tomas.Morissette@hotmail.com",
			address: { street: "4554 Mayert Isle", city: "Mizdah" },
		},
		{
			id: 33,
			full_name: "Moses Ondricka",
			email: "Moses_Ondricka57@gmail.com",
			address: { street: "624 Zieme Parkways", city: "Stung Treng" },
		},
		{
			id: 34,
			full_name: "Roberta Lowe",
			email: "Roberta_Lowe@gmail.com",
			address: { street: "442 Vidal Roads", city: "Balbasava" },
		},
		{
			id: 35,
			full_name: "Rachel Huel",
			email: "Rachel_Huel@gmail.com",
			address: { street: "321 Labadie Mission", city: "Saint-Henri" },
		},
		{
			id: 36,
			full_name: "Angel Littel",
			email: "Angel_Littel9@gmail.com",
			address: { street: "5505 Brian Viaduct", city: "Dassa-Zoumé" },
		},
		{
			id: 37,
			full_name: "Cody Carroll",
			email: "Cody98@gmail.com",
			address: { street: "948 Jones Flat", city: "Ordino" },
		},
		{
			id: 38,
			full_name: "Sheryl Barrows",
			email: "Sheryl76@gmail.com",
			address: { street: "0706 Durward Parkway", city: "Saint-Roman" },
		},
		{
			id: 39,
			full_name: "Isaac Schmeler",
			email: "Isaac.Schmeler27@hotmail.com",
			address: { street: "967 Kessler Harbor", city: "Belyye Vody" },
		},
		{
			id: 40,
			full_name: "Margie Rosenbaum",
			email: "Margie_Rosenbaum@gmail.com",
			address: { street: "43782 Margarett Spur", city: "Marigot" },
		},
		{
			id: 41,
			full_name: "Evelyn Pfeffer",
			email: "Evelyn80@gmail.com",
			address: { street: "362 Carmella Crescent", city: "Mahdia" },
		},
		{
			id: 42,
			full_name: "Lester Grady",
			email: "Lester44@hotmail.com",
			address: { street: "94874 Herminio Stravenue", city: "Chongjin" },
		},
		{
			id: 43,
			full_name: "Marco Krajcik",
			email: "Marco.Krajcik@hotmail.com",
			address: { street: "22580 Anita Flats", city: "Gulbene" },
		},
	],
};
